from typing import Protocol, Any


class CMClientProtocol(Protocol):
    def send_protobuf_message(
        self, emsg: Any, message: Any, steam_id: Any = None, job_id: Any = None
    ) -> Any: ...

    def next_job_id(self) -> int: ...

    def create_listener(self, event: Any, check: Any = None) -> Any: ...

    def create_stream_listener(self, event: Any, check: Any = None) -> Any: ...

    def remove_listener(self, event: Any, callback: Any) -> None: ...
